cases = {
    # region Document
    "document/test_doc_select_tool":  "Документы, рисование: проверка инструмента выделения",
    "document/test_doc_pen_green":  "Документы, рисование: проверка зеленой ручки",
    "document/test_doc_pen_red":  "Документы, рисование: проверка красной ручки",
    "document/test_doc_pen_yellow":  "Документы, рисование: проверка желтого маркера",
    "document/test_doc_eraser":  "Документы, рисование: проверка ластика",
    "document/test_doc_blank_page":  "Документы, вставка: проверка вставки пустой страницы",
    "document/test_doc_page_break":  "Документы, вставка: проверка вставки разрыва",
    "document/test_doc_insert_table":  "Документы, вставка: проверка вставки таблицы",
    "document/test_doc_insert_image":  "Документы, вставка: проверка вставки изображения",
    "document/test_doc_insert_chart":  "Документы, вставка: проверка вставки диаграммы",
    "document/test_doc_insert_shape":  "Документы, вставка: проверка вставки фигуры",
    "document/test_doc_insert_smartart":  "Документы, вставка: проверка вставки SmartArt",
    "document/test_doc_add_comment":  "Документы, вставка: проверка добавления комментария",
    "document/test_doc_add_hyperlink":  "Документы, вставка: проверка вставки гиперссылки",
    "document/test_doc_edit_header":  "Документы, вставка: проверка вставки колонтитулов",
    "document/test_doc_insert_datetime":  "Документы, вставка: проверка вставки даты и времени",
    "document/test_doc_insert_text":  "Документы, вставка: проверка вставки текстового поля",
    "document/test_doc_insert_textart":  "Документы, вставка: проверка вставки TextArt",
    "document/test_doc_insert_equation":  "Документы, вставка: проверка вставки уравнения",
    "document/test_doc_insert_symbol":  "Документы, вставка: проверка вставки символа",
    "document/test_doc_insert_dropcap":  "Документы, вставка: проверка вставки буквицы",
    "document/test_doc_insert_controls":  "Документы, вставка: проверка вставки элемента управления содержимым",
    "document/test_doc_page_margins":  "Документы, макет: проверка установки полей",
    "document/test_doc_page_orient":  "Документы, макет: проверка установки ориентации страницы",
    "document/test_doc_pagesize":  "Документы, макет: проверка установки размера страницы",
    "document/test_doc_columns":  "Документы, макет: проверка установки колонок",
    "document/test_doc_page_brake":  "Документы, макет: проверка разрыва страницы",
    "document/test_doc_line_numbers":  "Документы, макет: проверка нумерации строк",
    "document/test_doc_hyphenation":  "Документы, макет: проверка автопереносов",
    "document/test_doc_wrapping":  "Документы, макет: проверка обтекания текстом",
    "document/test_doc_move_backward":  "Документы, макет: проверка перенесения элемента назад",
    "document/test_doc_move_forward":  "Документы, макет: проверка перенесения элемента вперед",
    "document/test_doc_align":  "Документы, макет: проверка выравнивания",
    "document/test_doc_group":  "Документы, макет: проверка группировки",
    "document/test_doc_watermark":  "Документы, макет: проверка подложки",
    "document/test_doc_add_text":  "Документы, ссылки: проверка уровня текста",
    "document/test_doc_contents":  "Документы, ссылки: проверка оглавления",
    "document/test_doc_contents_update":  "Документы, ссылки: проверка обновления содержимого",
    "document/test_doc_notes":  "Документы, ссылки: проверка сносок",
    "document/test_doc_add_hyperlink_links":  "Документы, ссылки: проверка ссылок",
    "document/test_doc_bookmarks":  "Документы, ссылки: проверка закладок",
    "document/test_doc_caption":  "Документы, ссылки: проверка названий (подписей)",
    "document/test_doc_crossref":  "Документы, ссылки: проверка перекрестных ссылок",
    "document/test_new_doc":  "Документы: создание нового документа",
    "document/test_doc_font":  "Документы, главная: проверка установки шрифта (Asana)",
    "document/test_doc_fontsize":  "Документы, главная: проверка установки размера шрифта (20)",
    "document/test_doc_increase_fontsize":  "Документы, главная: увеличение размера шрифта",
    "document/test_doc_decrease_fontsize":  "Документы, главная: уменьшение размера шрифта",
    "document/test_doc_font_case":  "Документы, главная: смена регистра текста",
    "document/test_doc_bold_text":  "Документы, главная: проверка жирного текста",
    "document/test_doc_italic_text":  "Документы, главная: проверка курсива",
    "document/test_doc_underline_text":  "Документы, главная: проверка подчёркнутого текста",
    "document/test_doc_strikeout_text":  "Документы, главная: проверка зачёркнутого текста",
    "document/test_doc_superscript_text":  "Документы, главная: проверка надстрочного текста",
    "document/test_doc_subscript_text":  "Документы, главная: проверка подстрочного текста",
    "document/test_doc_highlight_text":  "Документы, главная: проверка выделения текста",
    "document/test_doc_color_text":  "Документы, главная: проверка смены цвета текста",
    "document/test_doc_markers":  "Документы, главная: проверка маркированного списка",
    "document/test_doc_numbering":  "Документы, главная: проверка нумерованного списка",
    "document/test_doc_multilevels":  "Документы, главная: проверка многоуровневого списка",
    "document/test_doc_incoffset":  "Документы, главная: проверка увеличения отступа",
    "document/test_doc_decoffset":  "Документы, главная: проверка уменьшения отступа",
    "document/test_doc_linespace":  "Документы, главная: проверка междустрочного интервала",
    "document/test_doc_align_left":  "Документы, главная: проверка выравнивания слева",
    "document/test_doc_align_center":  "Документы, главная: проверка выравнивания по центру",
    "document/test_doc_align_right":  "Документы, главная: проверка выравнивания справа",
    "document/test_doc_align_just":  "Документы, главная: проверка выравнивания по ширине",
    "document/test_doc_hidenchars":  "Документы, главная: проверка непечатаемых символов",
    "document/test_doc_paracolor":  "Документы, главная: проверка заливки",
    "document/test_doc_clearstyle":  "Документы, главная: проверка очистки стиля",
    "document/test_doc_colorschemas":  "Документы, главная: проверка цветовой схемы",
    "document/test_doc_copystyle":  "Документы, главная: проверка копирования стиля",
    "document/test_doc_text_style":  "Документы, главная: проверка установки стиля текста",
    "document/test_doc_review_add_comment":  "Документы, совместная работа: добавление комментария",
    "document/test_doc_review_remove_comment":  "Документы, совместная работа: удаление комментария",
    "document/test_doc_review_remove_current_comments":  "Документы, совместная работа: удалить текущие комментарии",
    "document/test_doc_review_remove_my_comments":  "Документы, совместная работа: удалить мои комментарии",
    "document/test_doc_review_remove_all_comments":  "Документы, совместная работа: удалить все комментарии",
    "document/test_doc_review_resolve_comment":  "Документы, совместная работа: решить комментарий",
    "document/test_doc_review_resolve_current_comments":  "Документы, совместная работа: решить текущие комментарии",
    "document/test_doc_review_resolve_my_comments":  "Документы, совместная работа: решить мои комментарии",
    "document/test_doc_review_resolve_all_comments":  "Документы, совместная работа: решить все комментарии",
    "document/test_doc_review_on":  "Документы, совместная работа: включение отслеживания изменений",
    "document/test_doc_review_for_me_on":  "Документы, совместная работа: включение отслеживания изменений для меня",
    "document/test_doc_view_source_doc":  "Документы, совместная работа: проверка отображения изменений",
    "document/test_doc_change_accept":  "Документы, совместная работа: проверка принятия изменений",
    "document/test_doc_current_change_accept":  "Документы, совместная работа: проверка принятия текущего изменения",
    "document/test_doc_change_reject":  "Документы, совместная работа: проверка отмены изменений",
    "document/test_doc_current_change_reject":  "Документы, совместная работа: проверка отмены текущего изменения",
    "document/test_doc_move_to_previous_change":  "Документы, совместная работа: к предыдущему изменению",
    "document/test_doc_move_to_next_change":  "Документы, совместная работа: к следующему изменению",
    "document/test_doc_view_navigator":  "Документы, вид: проверка заголовков",
    "document/test_doc_zoom_input":  "Документы, вид: проверка ввода масштаба",
    "document/test_doc_zoom_from_dropdown_menu":  "Документы, вид: смена масштаба из выпадающего списка",
    "document/test_doc_zoom_to_page":  "Документы, вид: масштаб по размеру страницы",
    "document/test_doc_zoom_to_width":  "Документы, вид: масштаб по ширине страницы",
    "document/test_doc_change_interface_theme":  "Документы, вид: смена темы",
    "document/test_doc_dark_document":  "Документы, вид: установка темного документа",
    "document/test_doc_toolbar":  "Документы, вид: отображение панели инструментов",
    "document/test_doc_statusbar":  "Документы, вид: отображение панели статуса",
    "document/test_doc_right_panel":  "Документы, вид: отображение правой панели",
    "document/test_doc_left_panel":  "Документы, вид: отображение левой панели",
    "document/test_doc_rulers":  "Документы, вид: отображение линеек",
    # endregion
    # region Presentation
    "presentation/test_presentation_pen_green":  "Презентации, рисование: проверка зеленой ручки",
    "presentation/test_presentation_pen_red":  "Презентации, рисование: проверка красной ручки",
    "presentation/test_presentation_pen_yellow":  "Презентации, рисование: проверка желтого маркера",
    "presentation/test_presentation_eraser":  "Презентации, рисование: проверка ластика",
    "presentation/test_presentation_select_tool":  "Презентации, рисование: проверка инструмента выделения",
    "presentation/test_presentation_insert_add_slide":  "Презентации, вставка: проверка добавления слайда",
    "presentation/test_presentation_insert_add_type_slide":  "Презентации, вставка: проверка добавления слайда с макетом",
    "presentation/test_presentation_insert_table":  "Презентации, вставка: проверка вставки таблицы",
    "presentation/test_presentation_insert_user_table":  "Презентации, вставка: пользовательская таблица",
    "presentation/test_presentation_insert_table_form":  "Презентации, вставка: таблица определенной формы",
    "presentation/test_presentation_insert_horizontal_text_by_btn":  "Презентации, вставка: горизонтальный текст (по кнопке)",
    "presentation/test_presentation_insert_horizontal_text_by_link":  "Презентации, вставка: горизонтальный текст (из меню)",
    "presentation/test_presentation_insert_vertical_text_by_link":  "Презентации, вставка: вертикальный текст",
    "presentation/test_presentation_insert_text_art":  "Презентации, вставка: TextArt",
    "presentation/test_presentation_insert_linked_image":  "Презентации, вставка: изображение по ссылке",
    "presentation/test_presentation_insert_chart":  "Презентации, вставка: диаграмма",
    "presentation/test_presentation_insert_smart_art":  "Презентации, вставка: SmartArt",
    "presentation/test_presentation_insert_shape":  "Презентации, вставка: фигура",
    "presentation/test_presentation_insert_shape_by_dropdown_btn":  "Презентации, вставка: фигура (выпадающий список)",
    "presentation/test_presentation_insert_comment":  "Презентации, вставка: добавление комментария",
    "presentation/test_presentation_insert_hyperlink":  "Презентации, вставка: ссылка",
    "presentation/test_presentation_insert_edit_header":  "Презентации, вставка: редактирование колонтитула",
    "presentation/test_presentation_insert_date_and_time":  "Презентации, вставка: дата и время",
    "presentation/test_presentation_insert_slide_number":  "Презентации, вставка: номер слайда",
    "presentation/test_presentation_insert_equation":  "Презентации, вставка: уравнение",
    "presentation/test_presentation_insert_equation_by_dropdown_btn":  "Презентации, вставка: уравнение (из выпадающего списка)",
    "presentation/test_presentation_insert_symbol":  "Презентации, вставка: символ",
    "presentation/test_new_presentation":  "Презентации: создание презентации",
    "presentation/test_presentation_font":  "Презентации, главная: смена шрифта текста",
    "presentation/test_presentation_font_size":  "Презентации, главная: смена размера текста",
    "presentation/test_presentation_increase_font_size":  "Презентации, главная: увеличение размера текста",
    "presentation/test_presentation_decrease_font_size":  "Презентации, главная: уменьшение размера текста",
    "presentation/test_presentation_font_case":  "Презентации, главная: смена регистра текста",
    "presentation/test_presentation_bold_text":  "Презентации, главная: проверка жирного текста",
    "presentation/test_presentation_italic_text":  "Презентации, главная: проверка курсива",
    "presentation/test_presentation_underline_text":  "Презентации, главная: проверка подчёркнутого текста",
    "presentation/test_presentation_strikeout_text":  "Презентации, главная: проверка зачёркнутого текста",
    "presentation/test_presentation_superscript_text":  "Презентации, главная: проверка надстрочного текста",
    "presentation/test_presentation_subscript_text":  "Презентации, главная: проверка подстрочного текста",
    "presentation/test_presentation_highlight_text":  "Презентации, главная: проверка выделения текста",
    "presentation/test_presentation_color_text":  "Презентации, главная: смена цвета текста",
    "presentation/test_presentation_markers_on":  "Презентации, главная: проверка маркированного списка",
    "presentation/test_presentation_numbering_on":  "Презентации, главная: проверка нумерованного списка",
    "presentation/test_presentation_incoffset":  "Презентации, главная: увеличение отступа",
    "presentation/test_presentation_decoffset":  "Презентации, главная: уменьшение отступа",
    "presentation/test_presentation_align_left":  "Презентации, главная: выравнивание слева",
    "presentation/test_presentation_align_center":  "Презентации, главная: выравнивание по центру",
    "presentation/test_presentation_align_right":  "Презентации, главная: выравнивание справа",
    "presentation/test_presentation_align_just":  "Презентации, главная: выравнивание по ширине",
    "presentation/test_presentation_linespace":  "Презентации, главная: проверка междустрочного интервала",
    "presentation/test_presentation_align_top":  "Презентации, главная: выравнивание по верхнему краю",
    "presentation/test_presentation_align_middle":  "Презентации, главная: вертик. выравнивание по центру",
    "presentation/test_presentation_align_bottom":  "Презентации, главная: выравнивание по нижнему краю",
    "presentation/test_presentation_one_column_text":  "Презентации, главная: текст в одну колонку",
    "presentation/test_presentation_two_columns_text":  "Презентации, главная: текст в две колонки",
    "presentation/test_presentation_three_columns_text":  "Презентации, главная: текст в три колонки",
    "presentation/test_presentation_horizontal_text_by_btn":  "Презентации, главная: горизонтальный текст (по кнопке)",
    "presentation/test_presentation_horizontal_text_by_link":  "Презентации, главная: горизонтальный текст (из меню)",
    "presentation/test_presentation_vertical_text_by_link":  "Презентации, главная: вертикальный текст",
    "presentation/test_presentation_insert_image_by_url":  "Презентации, главная: вставка изображения по URL",
    "presentation/test_presentation_insert_rectangle":  "Презентации, главная: вставка фигуры",
    "presentation/test_presentation_shape_arrange_back":  "Презентации, главная: перенос на задний план",
    "presentation/test_presentation_shape_align_left":  "Презентации, главная: выравнивание объекта влево",
    "presentation/test_presentation_clear_style":  "Презентации, главная: очистка стиля",
    "presentation/test_presentation_copy_style":  "Презентации, главная: копирование стиля",
    "presentation/test_presentation_color_schemas":  "Презентации, главная: проверка цветовой схемы",
    "presentation/test_presentation_slide_size":  "Презентации, главная: размер слайда",
    "presentation/test_presentation_style":  "Презентации, главная: выбор стиля",
    "presentation/test_presentation_change_slide_layout":  "Презентации, главная: изменение макета",
    "presentation/test_presentation_add_slide":  "Презентации, главная: добавление слайда",
    "presentation/test_presentation_add_type_slide":  "Презентации, главная: добавление слайда со стилем",
    "presentation/test_presentation_preview":  "Презентации, главная: проверка предварительного просмотра",
    "presentation/test_presentation_review_add_comment":  "Презентации, совместная работа: добавление комментария",
    "presentation/test_presentation_review_remove_comment":  "Презентации, совместная работа: удаление комментария",
    "presentation/test_presentation_review_remove_current_comments":  "Презентации, совместная работа: удалить текущие комментарии",
    "presentation/test_presentation_review_remove_my_comments":  "Презентации, совместная работа: удалить мои комментарии",
    "presentation/test_presentation_review_remove_all_comments":  "Презентации, совместная работа: удалить все комментарии",
    "presentation/test_presentation_review_resolve_comment":  "Презентации, совместная работа: решить комментарий",
    "presentation/test_presentation_review_resolve_current_comments":  "Презентации, совместная работа: решить текущие комментарии",
    "presentation/test_presentation_review_resolve_my_comments":  "Презентации, совместная работа: решить мои комментарии",
    "presentation/test_presentation_review_popover_resolve_all_comments":  "Презентации, совместная работа: решить все комментарии",
    "presentation/test_presentation_review_popover_resolve_comment":  "Презентации, совместная работа: решить комментарий (всплывающее окно)",
    "presentation/test_presentation_zoom_input":  "Презентации, вид: смена масштаба вводом",
    "presentation/test_presentation_zoom_by_dropdown_btn":  "Презентации, вид: смена масштаба из меню",
    "presentation/test_presentation_zoom_to_slide":  "Презентации, вид: масштаб по слайду",
    "presentation/test_presentation_zoom_to_width":  "Презентации, вид: масштаб по ширине",
    "presentation/test_presentation_change_interface_theme":  "Презентации, вид: сменить тему",
    "presentation/test_presentation_notes":  "Презентации, вид: отображение заметок",
    "presentation/test_presentation_rulers":  "Презентации, вид: отображение линеек",
    "presentation/test_presentation_guides":  "Презентации, вид: отображение направляющих (по кнопке)",
    "presentation/test_presentation_guides_by_dropdown_btn":  "Презентации, вид: отображение направляющих (из списка)",
    "presentation/test_presentation_grid_lines_by_dropdown_btn":  "Презентации, вид: отображение сетки (из списка)",
    "presentation/test_presentation_grid_lines":  "Презентации, вид: отображение сетки (по кнопке)",
    "presentation/test_presentation_user_grid_lines":  "Презентации, вид: отображение пользовательской сетки",
    "presentation/test_presentation_toolbar":  "Презентации, вид: отображение панели инструментов",
    "presentation/test_presentation_statusbar":  "Презентации, вид: отображение строки состояния",
    "presentation/test_presentation_left_panel":  "Презентации, вид: отображение левой панели",
    "presentation/test_presentation_right_panel":  "Презентации, вид: отображение правой панели",
    # endregion
    # region Spreadsheet
    "spreadsheet/test_receive_data_from_text_files":  "Таблицы, данные: получение данных из файла",
    "spreadsheet/test_show_external_links":  "Таблицы, данные: внешние ссылки",
    "spreadsheet/test_goal_seek":  "Таблицы, данные: подбор цели",
    "spreadsheet/test_insert_data_table_with_column_variable":  "Таблицы, данные: вставка таблицы с настраиваемой сортировкой",
    "spreadsheet/test_insert_auto_filter_in_data_tab":  "Таблицы, данные: работа автофильтра",
    "spreadsheet/test_clear_filter_in_data_tab":  "Таблицы, данные: очистка автофильтра",
    "spreadsheet/test_sort_descending_in_data_tab":  "Таблицы, данные: сортировка по убыванию",
    "spreadsheet/test_sort_ascending_in_data_tab":  "Таблицы, данные: сортировка по возрастанию",
    "spreadsheet/test_insert_text_to_columns":  "Таблицы, данные: текст по столбцам",
    "spreadsheet/test_remove_duplicates":  "Таблицы, данные: удаление дубликатов",
    "spreadsheet/test_validate_data":  "Таблицы, данные: проверка данных",
    "spreadsheet/test_group_area":  "Таблицы, данные: группировка",
    "spreadsheet/test_ungroup_area":  "Таблицы, данные: разгруппировка",
    "spreadsheet/test_sp_select_tool":  "Таблицы, рисование: проверка инструмента выделения",
    "spreadsheet/test_sp_pen_green":  "Таблицы, рисование: проверка зеленой ручки",
    "spreadsheet/test_sp_pen_red":  "Таблицы, рисование: проверка красной ручки",
    "spreadsheet/test_sp_pen_yellow":  "Таблицы, рисование: проверка желтого маркера",
    "spreadsheet/test_sp_eraser":  "Таблицы, рисование: проверка ластика",
    "spreadsheet/test_insert_additional_formula":  "Таблицы, формулы: вставка функции",
    "spreadsheet/test_insert_auto_sum":  "Таблицы, формулы: проверка автосуммы",
    "spreadsheet/test_insert_auto_sum_dropdown_average":  "Таблицы, формулы: автосумма, СРЗНАЧ",
    "spreadsheet/test_insert_recent_formula_sum":  "Таблицы, формулы: последняя использованная формула",
    "spreadsheet/test_insert_financial_formula_apl":  "Таблицы, формулы: финансовая формула, АПЛ",
    "spreadsheet/test_insert_logical_formula_if":  "Таблицы, формулы: логическая формула, ЕСЛИ",
    "spreadsheet/test_insert_text_formula_unicode":  "Таблицы, формулы: текстовая формула, UNICODE",
    "spreadsheet/test_insert_date_time_formula_date":  "Таблицы, формулы: формула Дата и время",
    "spreadsheet/test_insert_lookup_formula_dvssyl":  "Таблицы, формулы: формула поиска, ДВССЫЛ",
    "spreadsheet/test_insert_math_formula_cos":  "Таблицы, формулы: математическая формула, COS",
    "spreadsheet/test_insert_more_formula_engineering_besseli":  "Таблицы, формулы: инженерная функция, БЕССЕЛЬ.I",
    "spreadsheet/test_add_named_range_in_formula_tab":  "Таблицы, формулы: именованные диапазоны",
    "spreadsheet/test_add_watch_control_value":  "Таблицы, формулы: окно контрольных значений",
    "spreadsheet/test_calculate_formulas":  "Таблицы, формулы: пересчет формул",
    "spreadsheet/test_show_influencing_cells":  "Таблицы, формулы: влияющие ячейки",
    "spreadsheet/test_show_dependent_cells":  "Таблицы, формулы: зависимые ячейки",
    "spreadsheet/test_remove_link_arrows":  "Таблицы, формулы: убрать стрелки",
    "spreadsheet/test_show_formulas":  "Таблицы, формулы: показать формулы",
    "spreadsheet/test_insert_pivot_table":  "Таблицы, вставка: сводная таблица",
    "spreadsheet/test_insert_table":  "Таблицы, вставка: таблица",
    "spreadsheet/test_insert_image":  "Таблицы, вставка: изображение",
    "spreadsheet/test_insert_shape":  "Таблицы, вставка: фигура",
    "spreadsheet/test_insert_text":  "Таблицы, вставка: текст",
    "spreadsheet/test_insert_text_art":  "Таблицы, вставка: TextArt",
    "spreadsheet/test_insert_chart":  "Таблицы, вставка: диаграмма",
    "spreadsheet/test_insert_sparkline":  "Таблицы, вставка: спарклайн",
    "spreadsheet/test_insert_smart_art":  "Таблицы, вставка: SmartArt",
    "spreadsheet/test_add_comment":  "Таблицы, вставка: добавление комментария",
    "spreadsheet/test_insert_hyperlink":  "Таблицы, вставка: гиперссылка",
    "spreadsheet/test_insert_headers_footers":  "Таблицы, вставка: колонтитулы",
    "spreadsheet/test_insert_equation":  "Таблицы, вставка: уравнение",
    "spreadsheet/test_insert_symbol":  "Таблицы, вставка: символ",
    "spreadsheet/test_insert_slicers":  "Таблицы, вставка: срез",
    "spreadsheet/test_change_page_margins":  "Таблицы, макет: изменение полей",
    "spreadsheet/test_change_page_orient":  "Таблицы, макет: изменение ориентации",
    "spreadsheet/test_change_page_size":  "Таблицы, макет: изменение размера страницы",
    "spreadsheet/test_set_print_area":  "Таблицы, макет: задание области печати",
    "spreadsheet/test_remove_print_area":  "Таблицы, макет: удаление области печати",
    "spreadsheet/test_insert_page_breaks":  "Таблицы, макет: вставка разрыва",
    "spreadsheet/test_remove_page_breaks":  "Таблицы, макет: удаление разрыва",
    "spreadsheet/test_insert_headers_footers_layout_tab":  "Таблицы, макет: добавление колонтитулов",
    "spreadsheet/test_change_page_scale":  "Таблицы, макет: вписать страницу",
    "spreadsheet/test_print_table_titles":  "Таблицы, макет: проверка отображения заголовков (кнопка)",
    "spreadsheet/test_print_gridlines":  "Таблицы, макет: проверка отображения сетки",
    "spreadsheet/test_print_headings":  "Таблицы, макет: проверка отображения заголовков (флаг)",
    "spreadsheet/test_move_shape_forward":  "Таблицы, макет: перенос объекта вперед",
    "spreadsheet/test_move_shape_backward":  "Таблицы, макет: перенос объекта назад",
    "spreadsheet/test_align_shapes":  "Таблицы, макет: выравнивание объекта",
    "spreadsheet/test_group_shapes":  "Таблицы, макет: группировка объектов",
    "spreadsheet/test_ungroup_shapes":  "Таблицы, макет: разгруппировка объектов",
    "spreadsheet/test_change_color_schema":  "Таблицы, макет: смена цветовой схемы",
    "spreadsheet/test_input_font_name":  "Таблицы, главная: проверка ввода шрифта (Roboto)",
    "spreadsheet/test_change_font_name":  "Таблицы, главная: проверка шрифта из вып. списка (Asana)",
    "spreadsheet/test_input_font_size":  "Таблицы, главная: проверка ввода шрифта (18)",
    "spreadsheet/test_increase_font_size":  "Таблицы, главная: проверка увеличения шрифта",
    "spreadsheet/test_decrease_font_size":  "Таблицы, главная: проверка уменьшения шрифта",
    "spreadsheet/test_change_case_text":  "Таблицы, главная: смена регистра текста",
    "spreadsheet/test_bold_text":  "Таблицы, главная: проверка жирного шрифта",
    "spreadsheet/test_italic_text":  "Таблицы, главная: проверка курсива",
    "spreadsheet/test_underline_text":  "Таблицы, главная: проверка подчёркивания шрифта",
    "spreadsheet/test_strikeout_text":  "Таблицы, главная: проверка зачёркивания шрифта",
    "spreadsheet/test_subscript_text":  "Таблицы, главная: проверка надстрочного шрифта",
    "spreadsheet/test_superscript_text":  "Таблицы, главная: проверка подстрочного шрифта",
    "spreadsheet/test_font_color_red":  "Таблицы, главная: смена цвета шрифта",
    "spreadsheet/test_highlight_green":  "Таблицы, главная: проверка выделения шрифта",
    "spreadsheet/test_borders_all":  "Таблицы, главная: установка границ (все)",
    "spreadsheet/test_align_top":  "Таблицы, главная: выравнивание сверху",
    "spreadsheet/test_align_middle":  "Таблицы, главная: выравнивание посередине (вертикаль)",
    "spreadsheet/test_align_bottom":  "Таблицы, главная: выравнивание снизу",
    "spreadsheet/test_align_left":  "Таблицы, главная: выравнивание слева",
    "spreadsheet/test_align_center":  "Таблицы, главная: выравнивание по центру (горизонталь)",
    "spreadsheet/test_align_right":  "Таблицы, главная: выравнивание справа",
    "spreadsheet/test_align_just":  "Таблицы, главная: выравнивание по ширине",
    "spreadsheet/test_hyphenation":  "Таблицы, главная: перенос текста",
    "spreadsheet/test_orient_text":  "Таблицы, главная: ориентация текста",
    "spreadsheet/test_merge_cells":  "Таблицы, главная: объединение ячеек",
    "spreadsheet/test_insert_sum":  "Таблицы, главная: вставка суммы",
    "spreadsheet/test_add_named_range":  "Таблицы, главная: именованные диапазоны",
    "spreadsheet/test_sort_descending":  "Таблицы, главная: сортировка по убыванию",
    "spreadsheet/test_sort_ascending":  "Таблицы, главная: сортировка по возрастанию",
    "spreadsheet/test_insert_filter":  "Таблицы, главная: проверка фильтрации",
    "spreadsheet/test_clear_filter":  "Таблицы, главная: очистка фильтра",
    "spreadsheet/test_change_data_format":  "Таблицы, главная: смена формата данных",
    "spreadsheet/test_percents_data_format":  "Таблицы, главная: форматирование (проценты)",
    "spreadsheet/test_currency_data_format":  "Таблицы, главная: форматирование (денежный)",
    "spreadsheet/test_decrement_digits_data_format":  "Таблицы, главная: уменьшение разрядности",
    "spreadsheet/test_increment_digits_data_format":  "Таблицы, главная: увеличение разрядности",
    "spreadsheet/test_insert_cell_with_move_right":  "Таблицы, главная: вставка ячейки со сдвигом вправо",
    "spreadsheet/test_delete_cell_with_move_left":  "Таблицы, главная: вставка ячейки со сдвигом влево",
    "spreadsheet/test_clear_style_formating":  "Таблицы, главная: очистить стиль",
    "spreadsheet/test_copy_style":  "Таблицы, главная: копировать стиль",
    "spreadsheet/test_conditional_formating":  "Таблицы, главная: условное форматирование",
    "spreadsheet/test_insert_table_by_template":  "Таблицы, главная: форматирование по шаблону таблицы",
    "spreadsheet/test_change_field_style":  "Таблицы, главная: стиль поля",
    "spreadsheet/test_pivot_table":  "Таблицы, сводная таблица: вставить сводную таблицу",
    "spreadsheet/test_change_report_layout_structure_form":  "Таблицы, сводная таблица: макет отчета",
    "spreadsheet/test_insert_blank_row":  "Таблицы, сводная таблица: пустые строки",
    "spreadsheet/test_show_subtotals_in_footer":  "Таблицы, сводная таблица: промежуточные итоги",
    "spreadsheet/test_turn_on_grand_totals":  "Таблицы, сводная таблица: общие итоги",
    "spreadsheet/test_refresh_pivot_table":  "Таблицы, сводная таблица: обновить таблицу",
    "spreadsheet/test_insert_pivot_chart":  "Таблицы, сводная таблица: сводная диаграмма",
    "spreadsheet/test_select_all_pivot_table":  "Таблицы, сводная таблица: выделение таблицы",
    "spreadsheet/test_insert_calc_field":  "Таблицы, сводная таблица: вычисляемое поле",
    "spreadsheet/test_check_header_row_turn_off":  "Таблицы, сводная таблица: заголовки строк (выкл)",
    "spreadsheet/test_check_header_col_turn_off":  "Таблицы, сводная таблица: заголовки столбцов (выкл)",
    "spreadsheet/test_check_banded_row_turn_on":  "Таблицы, сводная таблица: чередование строк (вкл)",
    "spreadsheet/test_check_banded_col_turn_on":  "Таблицы, сводная таблица: чередование столбцов (вкл)",
    "spreadsheet/test_change_pivot_table_style":  "Таблицы, сводная таблица: стиль сводной таблицы",
    "spreadsheet/test_spreadsheet_review_add_comment":  "Таблицы, совместная работа: добавление комментария",
    "spreadsheet/test_spreadsheet_review_remove_comment":  "Таблицы, совместная работа: удаление комментария",
    "spreadsheet/test_spreadsheet_review_remove_current_comments":  "Таблицы, совместная работа: удалить текущие комментарии",
    "spreadsheet/test_spreadsheet_review_remove_my_comments":  "Таблицы, совместная работа: удалить мои комментарии",
    "spreadsheet/test_spreadsheet_review_remove_all_comments":  "Таблицы, совместная работа: удалить все комментарии",
    "spreadsheet/test_spreadsheet_review_resolve_comment":  "Таблицы, совместная работа: решить комментарий",
    "spreadsheet/test_spreadsheet_review_resolve_current_comments":  "Таблицы, совместная работа: решить текущие комментарии",
    "spreadsheet/test_spreadsheet_review_resolve_my_comments":  "Таблицы, совместная работа: решить мои комментарии",
    "spreadsheet/test_spreadsheet_review_resolve_all_comments":  "Таблицы, совместная работа: решить все комментарии",
    "spreadsheet/test_spreadsheet_zoom_input":  "Таблицы, вид: ввод масштаба",
    "spreadsheet/test_spreadsheet_zoom_from_dropdown_menu":  "Таблицы, вид: выбор масштаба из списка",
    "spreadsheet/test_spreadsheet_change_interface_theme":  "Таблицы, вид: смена темы интерфейса",
    "spreadsheet/test_spreadsheet_view":  "Таблицы, вид: создание представления листа",
    "spreadsheet/test_spreadsheet_close_view":  "Таблицы, вид: закрыть представление листа",
    "spreadsheet/test_spreadsheet_view_by_manager":  "Таблицы, вид: представление листа через менеджер",
    "spreadsheet/test_spreadsheet_view_page_brake":  "Таблицы, вид: страничный режим",
    "spreadsheet/test_spreadsheet_view_page_layout":  "Таблицы, вид: разметка страницы",
    "spreadsheet/test_spreadsheet_view_page_normal":  "Таблицы, вид: обычный режим",
    "spreadsheet/test_spreadsheet_freeze_area":  "Таблицы, вид: закрепление области",
    "spreadsheet/test_spreadsheet_remove_freeze_area":  "Таблицы, вид: снятие закрепления области",
    "spreadsheet/test_spreadsheet_freeze_row":  "Таблицы, вид: закрепление строки",
    "spreadsheet/test_spreadsheet_freeze_column":  "Таблицы, вид: закрепление столбца",
    "spreadsheet/test_spreadsheet_freeze_area_shadow":  "Таблицы, вид: тень для закрепленных областей",
    "spreadsheet/test_spreadsheet_freeze_row_shadow":  "Таблицы, вид: тень для закрепленных строк",
    "spreadsheet/test_spreadsheet_freeze_column_shadow":  "Таблицы, вид: тень для закрепленных столбцов",
    "spreadsheet/test_spreadsheet_formula_field":  "Таблицы, вид: флаг Строка формул",
    "spreadsheet/test_spreadsheet_heading":  "Таблицы, вид: флаг Заголовки",
    "spreadsheet/test_spreadsheet_grid_lines":  "Таблицы, вид: флаг Линии сетки",
    "spreadsheet/test_spreadsheet_zeros":  "Таблицы, вид: флаг Отображать нули",
    "spreadsheet/test_spreadsheet_rulers":  "Таблицы, вид: флаг Линейка",
    "spreadsheet/test_spreadsheet_toolbar":  "Таблицы, вид: отображение панели инструментов",
    "spreadsheet/test_spreadsheet_statusbar":  "Таблицы, вид: объединение строки листов и состояния",
    "spreadsheet/test_spreadsheet_left_panel":  "Таблицы, вид: отображение левой панели",
    "spreadsheet/test_spreadsheet_right_panel": "Таблицы, вид: отображение правой панели"
    # endregion
}
