from configs.config import ROOT_DIR


class ExpectedImagesWindows:
    # region Main Tab
    TEST_DOC_FONT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_font.png'
    TEST_DOC_FONTSIZE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_fontsize.png'
    TEST_DOC_INCREASE_FONTSIZE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_increase_fontsize.png'
    TEST_DOC_DECREASE_FONTSIZE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_decrease_fontsize.png'
    TEST_DOC_FONT_CASE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_font_case.png'
    TEST_DOC_BOLD_TEXT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_bold_text.png'
    TEST_DOC_ITALIC_TEXT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_italic_text.png'
    TEST_DOC_UNDERLINE_TEXT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_underline_text.png'
    TEST_DOC_STRIKEOUT_TEXT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_strikeout_text.png'
    TEST_DOC_SUPERSCRIPT_TEXT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_superscript_text.png'
    TEST_DOC_SUBSCRIPT_TEXT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_subscript_text.png'
    TEST_DOC_HIGHLIGHT_TEXT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_highlight_text.png'
    TEST_DOC_COLOR_TEXT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_color_text.png'
    TEST_DOC_MARKERS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_markers_on.png'
    TEST_DOC_NUMBERING = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_numbering_on.png'
    TEST_DOC_MULTILEVELS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_multilevels.png'
    TEST_DOC_DECOFFSET = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_decoffset.png'
    TEST_DOC_INCOFFSET = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_incoffset.png'
    TEST_DOC_LINESPACE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_linespace.png'
    TEST_DOC_ALIGN_LEFT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_align_left.png'
    TEST_DOC_ALIGN_CENTER = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_align_center.png'
    TEST_DOC_ALIGN_RIGHT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_align_right.png'
    TEST_DOC_ALIGN_JUST = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_align_just.png'
    TEST_DOC_HIDENCHARS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_hidenchars.png'
    TEST_DOC_PARACOLOR = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_paracolor.png'
    TEST_DOC_CLEARSTYLE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_clearstyle.png'
    TEST_DOC_COLORSCHEMAS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_colorschemas.png'
    TEST_DOC_COPYSTYLE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_copystyle.png'
    TEST_DOC_TEXT_STYLE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/main/test_doc_text_style.png'
    # endregion

    # region Insert Tab
    TEST_DOC_BLANK_PAGE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_blank_page.png'
    TEST_DOC_PAGE_BREAK = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_page_break.png'
    TEST_DOC_INSERT_TABLE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_insert_table.png'
    TEST_DOC_INSERT_IMAGE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_insert_image.png'
    TEST_DOC_INSERT_CHART = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_insert_chart.png'
    TEST_DOC_INSERT_SHAPE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_insert_shape.png'
    TEST_DOC_INSERT_SMARTART = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_insert_smartart.png'
    TEST_DOC_ADD_COMMENT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_add_comment.png'
    TEST_DOC_ADD_HYPERLINK = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_add_hyperlink.png'
    TEST_DOC_EDIT_HEADER = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_edit_header.png'
    TEST_DOC_INSERT_TEXT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_insert_text.png'
    TEST_DOC_INSERT_TEXTART = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_insert_textart.png'
    TEST_DOC_INSERT_EQUATION = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_insert_equation.png'
    TEST_DOC_INSERT_SYMBOL = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_insert_symbol.png'
    TEST_DOC_INSERT_DROPCAP = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_insert_dropcap.png'
    TEST_DOC_INSERT_CONTROLS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/insert/test_doc_insert_controls.png'
    # endregion

    # region Draw Tab
    TEST_DOC_SELECT_TOOL = ROOT_DIR + '/resources/document/expected_results_windows/tabs/draw/test_doc_select_tool.png'
    TEST_DOC_PEN_GREEN = ROOT_DIR + '/resources/document/expected_results_windows/tabs/draw/test_doc_pen_green.png'
    TEST_DOC_PEN_RED = ROOT_DIR + '/resources/document/expected_results_windows/tabs/draw/test_doc_pen_red.png'
    TEST_DOC_PEN_YELLOW = ROOT_DIR + '/resources/document/expected_results_windows/tabs/draw/test_doc_pen_yellow.png'
    TEST_DOC_ERASER = ROOT_DIR + '/resources/document/expected_results_windows/tabs/draw/test_doc_eraser.png'
    # endregion

    # region Layout Tab
    TEST_DOC_PAGE_MARGINS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/layout/test_doc_page_margins.png'
    TEST_DOC_PAGE_ORIENT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/layout/test_doc_page_orient.png'
    TEST_DOC_PAGESIZE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/layout/test_doc_pagesize.png'
    TEST_DOC_COLUMNS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/layout/test_doc_columns.png'
    TEST_DOC_PAGE_BRAKE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/layout/test_doc_page_brake.png'
    TEST_DOC_LINE_NUMBERS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/layout/test_doc_line_numbers.png'
    TEST_DOC_HYPHENATION = ROOT_DIR + '/resources/document/expected_results_windows/tabs/layout/test_doc_hyphenation.png'
    TEST_DOC_WRAPPING = ROOT_DIR + '/resources/document/expected_results_windows/tabs/layout/test_doc_wrapping.png'
    TEST_DOC_MOVE_BACKWARD = ROOT_DIR + '/resources/document/expected_results_windows/tabs/layout/test_doc_move_backward.png'
    TEST_DOC_MOVE_FORWARD = ROOT_DIR + '/resources/document/expected_results_windows/tabs/layout/test_doc_move_forward.png'
    TEST_DOC_ALIGN = ROOT_DIR + '/resources/document/expected_results_windows/tabs/layout/test_doc_align.png'
    TEST_DOC_GROUP = ROOT_DIR + '/resources/document/expected_results_windows/tabs/layout/test_doc_group.png'
    TEST_DOC_WATERMARK = ROOT_DIR + '/resources/document/expected_results_windows/tabs/layout/test_doc_watermark.png'
    # endregion

    # region Links Tab
    TEST_DOC_ADD_TEXT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/links/test_doc_add_text.png'
    TEST_DOC_CONTENTS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/links/test_doc_contents.png'
    TEST_DOC_CONTENTS_UPDATE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/links/test_doc_contents_update.png'
    TEST_DOC_NOTES = ROOT_DIR + '/resources/document/expected_results_windows/tabs/links/test_doc_notes.png'
    TEST_DOC_HYPERLINK_LINKS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/links/test_doc_hyperlink_links.png'
    TEST_DOC_BOOKMARKS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/links/test_doc_bookmarks.png'
    TEST_DOC_CAPTION = ROOT_DIR + '/resources/document/expected_results_windows/tabs/links/test_doc_caption.png'
    TEST_DOC_CROSSREF = ROOT_DIR + '/resources/document/expected_results_windows/tabs/links/test_doc_crossref.png'
    # endregion

    # region Review Tab
    TEST_DOC_REVIEW_ADD_COMMENT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_review_add_comment.png'
    TEST_DOC_REVIEW_REMOVE_COMMENT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_review_remove_comment.png'
    TEST_DOC_REMOVE_CURRENT_COMMENTS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_remove_current_comments.png'
    TEST_DOC_REMOVE_MY_COMMENTS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_remove_my_comments.png'
    TEST_DOC_REMOVE_ALL_COMMENTS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_remove_all_comments.png'
    TEST_DOC_RESOLVE_COMMENT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_resolve_comment.png'
    TEST_DOC_RESOLVE_CURRENT_COMMENTS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_resolve_current_comments.png'
    TEST_DOC_RESOLVE_MY_COMMENTS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_resolve_my_comments.png'
    TEST_DOC_RESOLVE_ALL_COMMENTS = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_resolve_all_comments.png'
    TEST_DOC_REVIEW_ON = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_review_on.png'
    TEST_DOC_REVIEW_FOR_ME_ON = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_review_for_me_on.png'
    TEST_DOC_VIEW_SOURCE_DOC = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_view_source_doc.png'
    TEST_DOC_CHANGE_ACCEPT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_change_accept.png'
    TEST_DOC_CURRENT_CHANGE_ACCEPT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_current_change_accept.png'
    TEST_DOC_CHANGE_REJECT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_change_reject.png'
    TEST_DOC_CURRENT_CHANGE_REJECT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_current_change_reject.png'
    TEST_DOC_MOVE_TO_PREVIOUS_CHANGE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_move_to_previous_change.png'
    TEST_DOC_MOVE_TO_NEXT_CHANGE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/review/test_doc_move_to_next_change.png'
    # endregion

    # region View Tab
    TEST_DOC_VIEW_NAVIGATOR = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_view_navigator.png'
    TEST_DOC_ZOOM_INPUT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_zoom_input.png'
    TEST_DOC_ZOOM_FROM_DROPDOWN_MENU = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_zoom_from_dropdown_menu.png'
    TEST_DOC_ZOOM_TO_PAGE = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_zoom_to_page.png'
    TEST_DOC_ZOOM_TO_WIDTH = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_zoom_to_width.png'
    TEST_DOC_CONTRAST_DARK_INTERFACE_THEME = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_contrast_dark_interface_theme.png'
    TEST_DOC_SYSTEM_INTERFACE_THEME = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_system_interface_theme.png'
    TEST_DOC_DARK_DOCUMENT = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_dark_document.png'
    TEST_DOC_DARK_DOCUMENT_SYSTEM_INTERFACE_THEME = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_dark_document_system_interface_theme.png'
    TEST_DOC_TOOLBAR_ON = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_toolbar_on.png'
    TEST_DOC_TOOLBAR_OFF = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_toolbar_off.png'
    TEST_DOC_STATUSBAR_ON = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_statusbar_on.png'
    TEST_DOC_STATUSBAR_OFF = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_statusbar_off.png'
    TEST_DOC_RIGHT_PANEL_ON = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_right_panel_on.png'
    TEST_DOC_RIGHT_PANEL_OFF = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_right_panel_off.png'
    TEST_DOC_LEFT_PANEL_ON = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_left_panel_on.png'
    TEST_DOC_LEFT_PANEL_OFF = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_left_panel_off.png'
    TEST_DOC_RULERS_ON = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_rulers_on.png'
    TEST_DOC_RULERS_OFF = ROOT_DIR + '/resources/document/expected_results_windows/tabs/view/test_doc_rulers_off.png'
    # endregion