from configs.config import ROOT_DIR


class ExpectedImagesMac:
    # region Main Tab
    TEST_SP_INPUT_FONT_NAME = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_input_font_name.png'
    TEST_SP_CHANGE_FONT_NAME = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_change_font_name.png'
    TEST_SP_INPUT_FONT_SIZE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_input_font_size.png'
    TEST_SP_INCREASE_FONT_SIZE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_increase_font_size.png'
    TEST_SP_DECREASE_FONT_SIZE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_decrease_font_size.png'
    TEST_SP_CHANGE_CASE_TEXT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_change_case_text.png'
    TEST_SP_BOLD_TEXT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_bold_text.png'
    TEST_SP_ITALIC_TEXT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_italic_text.png'
    TEST_SP_UNDERLINE_TEXT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_underline_text.png'
    TEST_SP_STRIKEOUT_TEXT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_strikeout_text.png'
    TEST_SP_SUBSCRIPT_TEXT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_subscript_text.png'
    TEST_SP_SUPERSCRIPT_TEXT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_superscript_text.png'
    TEST_SP_FONT_COLOR_RED = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_font_color_red.png'
    TEST_SP_HIGHLIGHT_GREEN = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_highlight_green.png'
    TEST_SP_BORDERS_ALL = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_borders_all.png'
    TEST_SP_ALIGN_TOP = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_align_top.png'
    TEST_SP_ALIGN_MIDDLE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_align_middle.png'
    TEST_SP_ALIGN_BOTTOM = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_align_bottom.png'
    TEST_SP_ALIGN_LEFT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_align_left.png'
    TEST_SP_ALIGN_CENTER = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_align_center.png'
    TEST_SP_ALIGN_RIGHT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_align_right.png'
    TEST_SP_ALIGN_JUST = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_align_just.png'
    TEST_SP_HYPHENATION = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_hyphenation.png'
    TEST_SP_ORIENT_TEXT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_orient_text.png'
    TEST_SP_MERGE_CELLS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_merge_cells.png'
    TEST_SP_INSERT_SUM = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_insert_sum.png'
    TEST_SP_ADD_NAMED_RANGE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_add_named_range.png'
    TEST_SP_SORT_DESCENDING = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_sort_descending.png'
    TEST_SP_SORT_ASCENDING = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_sort_ascending.png'
    TEST_SP_INSERT_FILTER = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_insert_filter.png'
    TEST_SP_CLEAR_FILTER = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_clear_filter.png'
    TEST_SP_CHANGE_DATA_FORMAT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_change_data_format.png'
    TEST_SP_PERCENTS_DATA_FORMAT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_percents_data_format.png'
    TEST_SP_CURRENCY_DATA_FORMAT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_currency_data_format.png'
    TEST_SP_DECREMENT_DIGITS_DATA_FORMAT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_decrement_digits_data_format.png'
    TEST_SP_INCREMENT_DIGITS_DATA_FORMAT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_increment_digits_data_format.png'
    TEST_SP_INSERT_CELL_WITH_MOVE_RIGHT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_insert_cell_with_move_right.png'
    TEST_SP_DELETE_CELL_WITH_MOVE_LEFT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_delete_cell_with_move_left.png'
    TEST_SP_CLEAR_STYLE_FORMATING = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_clear_style_formating.png'
    TEST_SP_COPY_STYLE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_copy_style.png'
    TEST_SP_CONDITIONAL_FORMATING = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_conditional_formating.png'
    TEST_SP_INSERT_TABLE_BY_TEMPLATE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_insert_table_by_template.png'
    TEST_SP_CHANGE_FIELD_STYLE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/main/test_sp_change_field_style.png'
    # endregion

    # region Insert Tab
    TEST_SP_INSERT_PIVOT_TABLE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_pivot_table.png'
    TEST_SP_INSERT_TABLE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_table.png'
    TEST_SP_INSERT_IMAGE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_image.png'
    TEST_SP_INSERT_SHAPE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_shape.png'
    TEST_SP_INSERT_TEXT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_text.png'
    TEST_SP_INSERT_TEXT_ART = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_text_art.png'
    TEST_SP_INSERT_CHART = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_chart.png'
    TEST_SP_INSERT_SPARKLINE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_sparkline.png'
    TEST_SP_INSERT_SMART_ART = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_smart_art.png'
    TEST_SP_ADD_COMMENT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_add_comment.png'
    TEST_SP_INSERT_HYPERLINK = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_hyperlink.png'
    TEST_SP_INSERT_HEADERS_FOOTERS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_headers_footers.png'
    TEST_SP_INSERT_EQUATION = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_equation.png'
    TEST_SP_INSERT_SYMBOL = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_symbol.png'
    TEST_SP_INSERT_SLICERS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/insert/test_sp_insert_slicers.png'
    # endregion

    # region Draw Tab
    TEST_SP_SELECT_TOOL = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/draw/test_sp_select_tool.png'
    TEST_SP_PEN_GREEN = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/draw/test_sp_pen_green.png'
    TEST_SP_PEN_RED = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/draw/test_sp_pen_red.png'
    TEST_SP_PEN_YELLOW = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/draw/test_sp_pen_yellow.png'
    TEST_SP_ERASER = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/draw/test_sp_eraser.png'
    # endregion

    # region Layout Tab
    TEST_SP_CHANGE_PAGE_MARGINS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_change_page_margins.png'
    TEST_SP_CHANGE_PAGE_ORIENT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_change_page_orient.png'
    TEST_SP_CHANGE_PAGE_SIZE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_change_page_size.png'
    TEST_SP_SET_PRINT_AREA = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_set_print_area.png'
    TEST_SP_REMOVE_PRINT_AREA = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_remove_print_area.png'
    TEST_SP_INSERT_PAGE_BREAKS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_insert_page_breaks.png'
    TEST_SP_REMOVE_PAGE_BREAKS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_remove_page_breaks.png'
    TEST_SP_INSERT_HEADERS_FOOTERS_LAYOUT_TAB = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_insert_headers_footers_layout_tab.png'
    TEST_SP_CHANGE_PAGE_SCALE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_change_page_scale.png'
    TEST_SP_PRINT_TABLE_TITLES = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_print_table_titles.png'
    TEST_SP_PRINT_GRIDLINES = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_print_gridlines.png'
    TEST_SP_PRINT_HEADINGS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_print_headings.png'
    TEST_SP_MOVE_SHAPE_FORWARD = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_move_shape_forward.png'
    TEST_SP_MOVE_SHAPE_BACKWARD = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_move_shape_backward.png'
    TEST_SP_ALIGN_SHAPES = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_align_shapes.png'
    TEST_SP_GROUP_SHAPES = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_group_shapes.png'
    TEST_SP_UNGROUP_SHAPES = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_ungroup_shapes.png'
    TEST_SP_CHANGE_COLOR_SCHEMA = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/layout/test_sp_change_color_schema.png'
    # endregion

    # region Formula Tab
    TEST_SP_INSERT_ADDITIONAL_FORMULA = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_insert_additional_formula.png'
    TEST_SP_INSERT_AUTO_SUM = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_insert_auto_sum.png'
    TEST_SP_INSERT_AUTO_SUM_DROPDOWN_AVERAGE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_insert_auto_sum_dropdown_average.png'
    TEST_SP_INSERT_RECENT_FORMULA_SUM = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_insert_recent_formula_sum.png'
    TEST_SP_INSERT_FINANCIAL_FORMULA_APL = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_insert_financial_formula_apl.png'
    TEST_SP_INSERT_LOGICAL_FORMULA_IF = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_insert_logical_formula_if.png'
    TEST_SP_INSERT_TEXT_FORMULA_UNICODE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_insert_text_formula_unicode.png'
    TEST_SP_INSERT_DATE_TIME_FORMULA_DATE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_insert_date_time_formula_date.png'
    TEST_SP_INSERT_LOOKUP_FORMULA_DVSSYL = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_insert_lookup_formula_dvssyl.png'
    TEST_SP_INSERT_MATH_FORMULA_COS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_insert_math_formula_cos.png'
    TEST_SP_INSERT_MORE_FORMULA_ENGINEERING_BESSELI = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_insert_more_formula_engineering_besseli.png'
    TEST_SP_ADD_NAMED_RANGE_IN_FORMULA_TAB = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_add_named_range_in_formula_tab.png'
    TEST_SP_ADD_WATCH_CONTROL_VALUE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_add_watch_control_value.png'
    TEST_SP_CALCULATE_FORMULAS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_calculate_formulas.png'
    TEST_SP_SHOW_INFLUENCING_CELLS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_show_influencing_cells.png'
    TEST_SP_SHOW_DEPENDENT_CELLS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_show_dependent_cells.png'
    TEST_SP_REMOVE_LINK_ARROWS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_remove_link_arrows.png'
    TEST_SP_SHOW_FORMULAS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/formula/test_sp_show_formulas.png'
    # endregion

    # region Data Tab
    TEST_SP_RECEIVE_DATA_FROM_TEXT_FILES = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/data/test_sp_receive_data_from_text_files.png'
    TEST_SP_SHOW_EXTERNAL_LINKS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/data/test_sp_show_external_links.png'
    TEST_SP_GOAL_SEEK = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/data/test_sp_goal_seek.png'
    TEST_SP_INSERT_DATA_TABLE_WITH_COLUMN_VARIABLE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/data/test_sp_insert_data_table_with_column_variable.png'
    TEST_SP_INSERT_AUTO_FILTER_IN_DATA_TAB = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/data/test_sp_insert_auto_filter_in_data_tab.png'
    TEST_SP_CLEAR_FILTER_IN_DATA_TAB = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/data/test_sp_clear_filter_in_data_tab.png'
    TEST_SP_SORT_DESCENDING_IN_DATA_TAB = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/data/test_sp_sort_descending_in_data_tab.png'
    TEST_SP_SORT_ASCENDING_IN_DATA_TAB = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/data/test_sp_sort_ascending_in_data_tab.png'
    TEST_SP_INSERT_TEXT_TO_COLUMNS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/data/test_sp_insert_text_to_columns.png'
    TEST_SP_REMOVE_DUPLICATES = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/data/test_sp_remove_duplicates.png'
    TEST_SP_VALIDATE_DATA = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/data/test_sp_validate_data.png'
    TEST_SP_GROUP_AREA = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/data/test_sp_group_area.png'
    TEST_SP_UNGROUP_AREA = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/data/test_sp_ungroup_area.png'
    # endregion

    # region Pivot Table Tab
    TEST_SP_INSERT_PIVOT_TABLE_IN_PIVOT_TABLE_TAB = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_insert_pivot_table_in_pivot_table_tab.png'
    TEST_SP_CHANGE_REPORT_LAYOUT_STRUCTURE_FORM = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_change_report_layout_structure_form.png'
    TEST_SP_INSERT_BLANK_ROW = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_insert_blank_row.png'
    TEST_SP_SHOW_SUBTOTALS_IN_FOOTER = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_show_subtotals_in_footer.png'
    TEST_SP_TURN_ON_GRAND_TOTALS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_turn_on_grand_totals.png'
    TEST_SP_REFRESH_PIVOT_TABLE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_refresh_pivot_table.png'
    TEST_SP_INSERT_PIVOT_CHART = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_insert_pivot_chart.png'
    TEST_SP_SELECT_ALL_PIVOT_TABLE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_select_all_pivot_table.png'
    TEST_SP_INSERT_CALC_FIELD = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_insert_calc_field.png'
    TEST_SP_CHECK_HEADER_ROW_TURN_OFF = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_check_header_row_turn_off.png'
    TEST_SP_CHECK_HEADER_COL_TURN_OFF = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_check_header_col_turn_off.png'
    TEST_SP_CHECK_BANDED_ROW_TURN_ON = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_check_banded_row_turn_on.png'
    TEST_SP_CHECK_BANDED_COL_TURN_ON = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_check_banded_col_turn_on.png'
    TEST_SP_CHANGE_PIVOT_TABLE_STYLE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/pivot_table/test_sp_change_pivot_table_style.png'
    # endregion

    # region Review Tab
    TEST_SPREADSHEET_REVIEW_ADD_COMMENT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_add_comment.png'
    TEST_SPREADSHEET_REVIEW_REMOVE_COMMENT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_remove_comment.png'
    TEST_SPREADSHEET_REVIEW_REMOVE_CURRENT_COMMENTS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_remove_current_comments.png'
    TEST_SPREADSHEET_REVIEW_REMOVE_MY_COMMENTS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_remove_my_comments.png'
    TEST_SPREADSHEET_REVIEW_REMOVE_ALL_COMMENTS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_remove_all_comments.png'
    TEST_SPREADSHEET_REVIEW_RESOLVE_COMMENT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_resolve_comment.png'
    TEST_SPREADSHEET_REVIEW_RESOLVE_CURRENT_COMMENTS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_resolve_current_comments.png'
    TEST_SPREADSHEET_REVIEW_RESOLVE_MY_COMMENTS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_resolve_my_comments.png'
    TEST_SPREADSHEET_REVIEW_RESOLVE_ALL_COMMENTS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_resolve_all_comments.png'
    TEST_SPREADSHEET_REVIEW_POPOVER_ADD_REPLY_COMMENT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_popover_add_reply_comment.png'
    TEST_SPREADSHEET_REVIEW_LEFT_MENU_ADD_REPLY_COMMENT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_left_menu_add_reply_comment.png'
    TEST_SPREADSHEET_REVIEW_POPOVER_EDIT_COMMENT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_popover_edit_comment.png'
    TEST_SPREADSHEET_REVIEW_LEFT_MENU_EDIT_COMMENT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_left_menu_edit_comment.png'
    TEST_SPREADSHEET_REVIEW_POPOVER_REMOVE_COMMENT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_popover_remove_comment.png'
    TEST_SPREADSHEET_REVIEW_LEFT_MENU_REMOVE_COMMENT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_left_menu_remove_comment.png'
    TEST_SPREADSHEET_REVIEW_POPOVER_RESOLVE_COMMENT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_popover_resolve_comment.png'
    TEST_SPREADSHEET_REVIEW_LEFT_MENU_RESOLVE_COMMENT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/review/test_spreadsheet_review_left_menu_resolve_comment.png'
    # endregion

    # region View Tab
    TEST_SPREADSHEET_ZOOM_INPUT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_zoom_input.png'
    TEST_SPREADSHEET_ZOOM_FROM_DROPDOWN_MENU = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_zoom_from_dropdown_menu.png'
    TEST_SPREADSHEET_CHANGE_INTERFACE_THEME = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_change_interface_theme.png'
    TEST_SPREADSHEET_VIEW = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_view.png'
    TEST_SPREADSHEET_CLOSE_VIEW = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_close_view.png'
    TEST_SPREADSHEET_VIEW_BY_MANAGER = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_view_by_manager.png'
    TEST_SPREADSHEET_VIEW_PAGE_BRAKE = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_view_page_brake.png'
    TEST_SPREADSHEET_VIEW_PAGE_LAYOUT = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_view_page_layout.png'
    TEST_SPREADSHEET_VIEW_PAGE_NORMAL = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_view_page_normal.png'
    TEST_SPREADSHEET_FREEZE_AREA = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_freeze_area.png'
    TEST_SPREADSHEET_REMOVE_FREEZE_AREA = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_remove_freeze_area.png'
    TEST_SPREADSHEET_FREEZE_ROW = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_freeze_row.png'
    TEST_SPREADSHEET_FREEZE_COLUMN = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_freeze_column.png'
    TEST_SPREADSHEET_FREEZE_AREA_SHADOW = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_freeze_area_shadow.png'
    TEST_SPREADSHEET_FREEZE_ROW_SHADOW = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_freeze_row_shadow.png'
    TEST_SPREADSHEET_FREEZE_COLUMN_SHADOW = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_freeze_column_shadow.png'
    TEST_SPREADSHEET_FORMULA_FIELD = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_formula_field.png'
    TEST_SPREADSHEET_HEADING = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_heading.png'
    TEST_SPREADSHEET_GRID_LINES = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_grid_lines.png'
    TEST_SPREADSHEET_ZEROS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_zeros.png'
    TEST_SPREADSHEET_RULERS = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_rulers.png'
    TEST_SPREADSHEET_TOOLBAR = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_toolbar.png'
    TEST_SPREADSHEET_STATUSBAR = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_statusbar.png'
    TEST_SPREADSHEET_LEFT_PANEL = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_left_panel.png'
    TEST_SPREADSHEET_RIGHT_PANEL = ROOT_DIR + '/resources/spreadsheet/expected_results_mac/tabs/view/test_spreadsheet_right_panel.png'
    # endregion
